### ISSUE TITLE
Error while grabbing book

### ISSUE THREAD

**Issue by pfei-sa** [bebound/linovel#13]
Here is the output

``` python
python linovel.py http://www.linovel.com/n/book/6871.html
Getting:http://www.linovel.com/n/book/6871.html
错误 list index out of range
At:http://www.linovel.com/n/book/6871.html
Traceback (most recent call last):
  File "linovel.py", line 164, in <module>
    sys.exit(main())
  File "linovel.py", line 157, in main
    start(urls, output_dir, cover_path, out_format)
  File "linovel.py", line 133, in start
    grab_volume(url, output_dir, cover_path, out_format)
  File "linovel.py", line 86, in grab_volume
    raise e
  File "linovel.py", line 80, in grab_volume
    novel.get_novel_information()
  File "/Users/Akatsuki/PycharmProjects/linovel/novel.py", line 231, in get_novel_information
    self.extract_epub_info()
  File "/Users/Akatsuki/PycharmProjects/linovel/novel.py", line 132, in extract_epub_info
    self.find_volume_name_number(soup)
  File "/Users/Akatsuki/PycharmProjects/linovel/novel.py", line 83, in find_volume_name_number
    name = soup.select('h1')[1].string.strip()
IndexError: list index out of range
```

**Comment by pfei-sa** [comment]
School blocked linovel.com
I was not noticed
:(
