### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by maoyuhoatianqi** [bebound/linovel#22]
Download wenku8 return the same Error information due to its update.

[root@localhost linovel-master]# python3 linovel.py http://www.wenku8.com/book/1997.htm
Traceback (most recent call last):
  File "linovel.py", line 91, in <module>
    sys.exit(main())
  File "linovel.py", line 84, in main
    start(urls, output_dir, cover_path, out_format)
  File "linovel.py", line 58, in start
    novel.extract_novel_information()
  File "/root/Desktop/linovel-master/novel_wenku8.py", line 199, in extract_novel_information
    self.parse_vollist()
  File "/root/Desktop/linovel-master/novel_wenku8.py", line 194, in parse_vollist
    self.extract_common_information(soup)
  File "/root/Desktop/linovel-master/novel_wenku8.py", line 152, in extract_common_information
    self.book_name = self.get_book_name(soup)
  File "/root/Desktop/linovel-master/novel_wenku8.py", line 132, in get_book_name
    return re.search(r'《(.*)》小说打包', str(soup)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by maoyuhoatianqi** [comment]
and it also doesnt work on 360° novel

[root@localhost linovel-master]# python3 linovel.py http://qitawenku.360dxs.com/book_5164.html
第一卷 
Start parsing chapters
转载信息
错误 list index out of range 
At: http://qitawenku.360dxs.com/chapter_337332992.html
第1章 恋情的开
错误 list index out of range 
At: http://qitawenku.360dxs.com/chapter_337332994.html
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 88, in extract_chapter
    raise e
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 83, in extract_chapter
    chapter_content = self.get_chapter_content(str(soup))
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 57, in get_chapter_content
    src)[1].strip()
IndexError: list index out of range

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 88, in extract_chapter
    raise e
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 83, in extract_chapter
    chapter_content = self.get_chapter_content(str(soup))
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 57, in get_chapter_content
    src)[1].strip()
IndexError: list index out of range

序章
错误 list index out of range 
At: http://qitawenku.360dxs.com/chapter_337332993.html
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 88, in extract_chapter
    raise e
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 83, in extract_chapter
    chapter_content = self.get_chapter_content(str(soup))
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 57, in get_chapter_content
    src)[1].strip()
IndexError: list index out of range

第1章 恋情的开
错误 list index out of range 
At: http://qitawenku.360dxs.com/chapter_338417073.html
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 88, in extract_chapter
    raise e
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 83, in extract_chapter
    chapter_content = self.get_chapter_content(str(soup))
  File "/root/Desktop/linovel-master/novel_360dxs.py", line 57, in get_chapter_content
    src)[1].strip()
IndexError: list index out of range

Extract 可喜可贺，我进化成了美少女  completed
Generating 可喜可贺，我进化成了美少女  第一卷 
Start downloading pictures, total number:1
1/1[############################################################]

已生成：可喜可贺，我进化成了美少女  第一卷 .epub
